---
title: "Estimation of Daily Water Temperature using Dense Neural Networks"
author: "B Steele"
date: today
date-format: long
format: pdf
editor: 
  visual:
    theme: sky
---

```{r, env-set-up}
library(tidyverse)
library(reticulate)
library(kableExtra)
library(feather)

# file paths
is_dir = '~/OneDrive - Colostate/NASA-Northern/data/waterQuality/harmonized/'
rs_dir = '~/OneDrive - Colostate/NASA-Northern/data/remoteSensing/estimates/'
nn_dir = '~/OneDrive - Colostate/NASA-Northern/data/NN_train_val_test/regional_daily_temp/'
```

## Read in temp data and make train-val-test

```{r, raw_data}
# read in temp data
NW_temp <- read_csv(file.path(is_dir, 'manual_temperature_data_NW_harmonized_2024-01-01.csv'))
surf_temp <- NW_temp %>% 
  filter(depth <= 1) %>% 
  arrange(depth) %>% 
  slice(1, .by = c(date, station)) %>% 
  filter(station %in% c("CL-DAM1", "GL-MID", "GR-DAM", "HT-SOL",  "SM-MID", "WC-DAM", "WG-DAM")) %>%
  filter(date < ymd("2024-01-01")) 

NW_estimates <- read_csv(file.path(rs_dir, 'SurfTemp_linearCorrection_v2024-10-15.csv')) %>% 
  rename(feature = GNIS_Name) %>% 
  mutate(value = adj_temp_degC,
         feature = case_when(feature == 'Lake Granby' ~ 'Granby Reservoir',
                             feature == 'Carter Lake Reservoir' ~ 'Carter Lake',
                             feature == 'Shadow Mountain Lake' ~ 'Shadow Mountain Reservoir',
                             TRUE ~ feature)) %>% 
  filter(station %in% c("CL-DAM1", "GL-MID", "GR-DAM", "SM-MID", "HT-SOL") |
           (is.na(station) &
              location_type == "poi_center" &
              feature %in% c("Boulder Reservoir", "Green Mountain Reservoir", "Lake Estes")))

all_NW_temp <- full_join(surf_temp, NW_estimates) %>% 
  select(feature, station, value, date) %>% 
  filter(between(month(date), 5, 10))

# idiot check
ggplot(all_NW_temp, aes(x = date, y = value)) +
  geom_point() +
  facet_grid(feature ~. )

# weather data
weather <- read_feather('~/Desktop/g_NLDAS_prev_day_summaries.feather') %>% 
  pivot_longer(cols = c('tot_precip_mm', 'max_temp_degC', 'mean_temp_degC', 
                        'min_temp_degC', 'tot_sol_rad_Wpm2', 'min_wind_mps',
                        'mean_wind_mps', 'max_wind_mps'),
               names_to = 'variable') %>% 
  pivot_wider(names_from = c('variable', 'n_prev_days'),
              names_sep = '_',
              values_from = 'value') %>% 
  mutate(feature = case_when(feature == "Boulder" ~ "Boulder Reservoir",
                             feature == "Carter" ~ "Carter Lake",
                             feature == "Grand" ~ "Grand Lake",
                             feature == "GreenMountain" ~ "Green Mountain Reservoir",
                             feature == "Horsetooth" ~ "Horsetooth Reservoir",
                             feature == "Estes" ~ "Lake Estes",
                             feature == "Granby" ~ "Granby Reservoir",
                             feature == "ShadowMountain" ~ "Shadow Mountain Reservoir",
                             feature == "WillowCreek" ~ "Willow Creek Reservoir",
                             feature == "WindyGap" ~ "Windy Gap Reservoir",
                             .default = feature))

# # and cumulative sum weather
# met_cumulative_sum <- read_csv("~/OneDrive - Colostate/NASA-Northern/data/climate/aggregated/NW_NLDAS_climate_cumulative_sums_annual_1984-01-01_2023-05-17v2023-11-08.csv") %>%
#   rename(feature = lake) %>% 
#   mutate(feature = if_else(feature == 'Lake Granby',
#                            'Granby Reservoir',
#                            feature))

# static
static <- read_csv('~/OneDrive - Colostate/NASA-Northern/data/static_vars/static_vars.csv')

# join together for full dataset
full_dataset = left_join(static, all_NW_temp) %>%
  left_join(., weather) %>% 
  select(-station) %>% 
  arrange(date) %>%
  filter(complete.cases(.))

```

## Make train-val-test sets

Test data will be from 2022 forward (2y of data)

```{r, test-r}
# pull out test set (2021-01-01 forward)
test <- full_dataset %>% 
  filter(date >= ymd('2022-01-01')) 
write_csv(test, file.path(nn_dir, paste0('test_2022_v', Sys.Date(), '.csv')))

#full training set
training <- anti_join(full_dataset, test)

write_csv(training, file.path(nn_dir, paste0('training_2022_v', Sys.Date(), '.csv')))

```

